# Copyright (C) iNuron - info@openvstorage.com
# This file is part of Open vStorage. For license information, see <LICENSE.txt>

from __future__ import absolute_import

# Result codes
# Success return code
RESULT_SUCCESS = 0x0000

# Protocol version
PROTOCOL_VERSION = 0x00000001


class Request(object):
    """
    Wrapper for data requests generated by :meth:`Type.receive`
    """

    __slots__ = '_count',

    def __init__(self, count):
        self._count = count

    def __repr__(self):
        return 'Request(%d)' % self.count

    @property
    def count(self):
        """
        Number of requested bytes
        """
        return self._count


class Result(object):
    """
    Wrapper for value results generated by :meth:`Type.receive`
    """

    __slots__ = '_value',

    def __init__(self, value):
        self._value = value

    def __repr__(self):
        return 'Result(%r)' % self.value

    @property
    def value(self):
        """
        Result value
        """
        return self._value
