# Copyright (C) 2019 iNuron NV
#
# This file is part of Open vStorage Open Source Edition (OSE),
# as available from
#
#      http://www.openvstorage.org and
#      http://www.openvstorage.com.
#
# This file is free software; you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License v3 (GNU AGPLv3)
# as published by the Free Software Foundation, in version 3 as it comes
# in the LICENSE.txt file of the Open vStorage OSE distribution.
#
# Open vStorage is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY of any kind.

# Result codes
# Success return code
RESULT_SUCCESS = 0x0000

# Protocol version
PROTOCOL_VERSION = 0x00000001


class Request(object):
    """
    Wrapper for data requests generated by :meth:`Type.receive`
    """

    __slots__ = '_count',

    def __init__(self, count):
        self._count = count

    def __repr__(self):
        return 'Request(%d)' % self.count

    @property
    def count(self):
        """
        Number of requested bytes
        """
        return self._count


class Result(object):
    """
    Wrapper for value results generated by :meth:`Type.receive`
    """

    __slots__ = '_value',

    def __init__(self, value):
        self._value = value

    def __repr__(self):
        return 'Result(%r)' % self.value

    @property
    def value(self):
        """
        Result value
        """
        return self._value
